### ISSUE TITLE
mysql建表语句发一个呗，all_funds、histories

### ISSUE THREAD

**Issue by aircov** [ZxZ7/ZFundPredictor#2]

**Comment by ZxZ7** [comment]
建表语句没存

**Comment by aircov** [comment]
> 建表语句没存

数据库还在吗，desc一下 ：）

**Comment by ZxZ7** [comment]
mysql> desc histories;
+----------+--------------+------+-----+---------+-------+
| Field    | Type         | Null | Key | Default | Extra |
+----------+--------------+------+-----+---------+-------+
| fticker  | varchar(25)  | NO   | PRI | NULL    |       |
| hdate    | date         | NO   | PRI | NULL    |       |
| nav      | decimal(7,4) | YES  |     | NULL    |       |
| accu_nav | decimal(7,4) | YES  |     | NULL    |       |
| r_d      | decimal(5,2) | YES  |     | NULL    |       |
+----------+--------------+------+-----+---------+-------+


mysql> desc all_funds;
+--------------------+--------------+------+-----+---------+----------------+
| Field              | Type         | Null | Key | Default | Extra          |
+--------------------+--------------+------+-----+---------+----------------+
| id                 | int(11)      | NO   | PRI | NULL    | auto_increment |
| fticker            | varchar(25)  | NO   | UNI | NULL    |                |
| fname              | varchar(50)  | YES  |     | NULL    |                |
| ftype              | varchar(20)  | YES  |     | NULL    |                |
| current_style      | varchar(20)  | YES  |     | NULL    |                |
| date               | date         | YES  |     | NULL    |                |
| sharp_1y           | decimal(5,2) | YES  |     | NULL    |                |
| sharp_2y           | decimal(5,2) | YES  |     | NULL    |                |
| sharp_3y           | decimal(5,2) | YES  |     | NULL    |                |
| stdev_1y           | decimal(5,2) | YES  |     | NULL    |                |
| stdev_2y           | decimal(5,2) | YES  |     | NULL    |                |
| stdev_3y           | decimal(5,2) | YES  |     | NULL    |                |
| recent_1m          | decimal(5,2) | YES  |     | NULL    |                |
| recent_3m          | decimal(5,2) | YES  |     | NULL    |                |
| recent_6m          | decimal(5,2) | YES  |     | NULL    |                |
| recent_1y          | decimal(5,2) | YES  |     | NULL    |                |
| recent_2y          | decimal(5,2) | YES  |     | NULL    |                |
| recent_3y          | decimal(5,2) | YES  |     | NULL    |                |
| current_nav        | decimal(7,4) | YES  |     | NULL    |                |
| current_r_d        | decimal(7,4) | YES  |     | NULL    |                |
| current_net_assets | decimal(5,2) | YES  |     | NULL    |                |
| last_net_assets    | decimal(5,2) | YES  |     | NULL    |                |
| last2_net_assets   | decimal(5,2) | YES  |     | NULL    |                |
| current_stocks     | decimal(5,2) | YES  |     | NULL    |                |
| current_bonds      | decimal(5,2) | YES  |     | NULL    |                |
| current_cash       | decimal(5,2) | YES  |     | NULL    |                |
| industry_1         | varchar(45)  | YES  |     | NULL    |                |
| industry_1_pct     | decimal(5,2) | YES  |     | NULL    |                |
| industry_2         | varchar(45)  | YES  |     | NULL    |                |
| industry_2_pct     | decimal(5,2) | YES  |     | NULL    |                |
| industry_3         | varchar(45)  | YES  |     | NULL    |                |
| industry_3_pct     | decimal(5,2) | YES  |     | NULL    |                |
| industry_4         | varchar(45)  | YES  |     | NULL    |                |
| industry_4_pct     | decimal(5,2) | YES  |     | NULL    |                |
| industry_5         | varchar(45)  | YES  |     | NULL    |                |
| industry_5_pct     | decimal(5,2) | YES  |     | NULL    |                |
| manager_ranking    | decimal(5,4) | YES  |     | NULL    |                |
+--------------------+--------------+------+-----+---------+----------------+
